# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

myname: gaoxingaa.github.io
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
future: true

markdown: kramdown
title: Keep Learning
description: To Be a Fullstack Programmer
author:
  name: Jane

mooc_path: moocs/home.html
rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
BASE_PATH: https://gaoxingaa.github.io
production_url: https://gaoxingaa.github.io
